---
- name: Install Maria DB and create test DB
  hosts: web
  become: true
  vars:
    mysql_root_password: password

  tasks:
  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: present

  - name: Install pip3
    yum:
      name: python3-pip
      state: present
  
  - name: Install the Python MySQL Support Libraries
    pip:
      name: PyMySQL
      state: latest

  - name: Start mysql & enable it on reboot
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Update MySQL root password
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  
  - name: Copy the root credentials as .my.cnf file
    template:
      src: root.cnf.j2
      dest: ~/.my.cnf
      mode: 0600

  - name: Create a test DB
    mysql_db:
      name: MyNewDB
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"