---
- name: Install wordpress
  hosts: web
  become: yes

  tasks:
  - name: Installing latest version of MySQL native driver, PHP, MariaDB, Apache webserver
    dnf:
      name:
        - php-mysqlnd
        - php-fpm
        - mariadb-server
        - httpd
        - firewalld
      state: latest

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Enable port 80
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
