---
- name: Install wordpress
  hosts: web
  become: yes

  tasks:
  - name: Installing latest version of MySQL native driver, PHP, MariaDB, Apache webserver
    dnf:
      name:
        - php-mysqlnd
        - php-fpm
        - mariadb-server
        - httpd
      state: latest
 
  - name: Permitting http traffic
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled