---
- name: Install wordpress
  hosts: web
  become: yes

  tasks:
  - name: Installing latest version of MySQL native driver, PHP, MariaDB, Apache webserver. firewalld
    dnf:
      name:
        - php-mysqlnd
        - php-fpm
        - mariadb-server
        - httpd
        - firewalld
        - PyMySQL
        - MySQLdb
      state: latest

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Enable port 80
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled

  - name: Start httpd & MariaDB
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - mariadb

 # - name: Creating database
   # community.mysql.mysql_query:
    #query:
    #- CREATE DATABASE wordpress;
    #- CREATE USER `admin`@`localhost` IDENTIFIED BY `pass`;
    #- GRANT ALL ON wordpress.* TO `admin`@`localhost`;
   # - FLUSH PRIVILEGES;
    

  
